import shutil
import os

# Source images generated by the tool
sources = {
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\foundation_cover_1778916771424.png': 'books/covers/foundation.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\fluent_python_cover_1778916786440.png': 'books/covers/fluent_python.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\lotr_cover_1778916805861.png': 'books/covers/lotr.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\psychology_of_money_cover_1778916825068.png': 'books/covers/psychology_of_money.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\library_hero_banner_1778917026008.png': 'banners/library_hero.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\dune_cover_1778917087564.png': 'books/covers/dune.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\atomic_habits_cover_1778917104483.png': 'books/covers/atomic_habits.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\gatsby_cover_1778917120761.png': 'books/covers/gatsby.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\harry_potter_cover_1778917138295.png': 'books/covers/harry_potter.png',
    r'C:\Users\ELCOT\.gemini\antigravity\brain\acbc9ec2-7b54-4907-baa8-5cffe2c1096e\clean_code_cover_1778917155477.png': 'books/covers/clean_code.png'
}

target_root = r'd:\Library Management System\media'

for src, rel_path in sources.items():
    dest = os.path.join(target_root, rel_path)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    try:
        shutil.copy(src, dest)
        print(f"✅ Copied {rel_path}")
    except Exception as e:
        print(f"❌ Error copying {rel_path}: {e}")
